### ISSUE TITLE
Uploading a photo to Wikipedia

### ISSUE THREAD

**Issue by junaruga** [brickbots/framedeck#2]
Hello,

Thank you for your project. It's very cool. I am editing [Framework's Wikipedia page](https://en.wikipedia.org/wiki/Framework_Computer). And I would like to see [this photo, images/framework_logo.jpeg](https://github.com/brickbots/framedeck/blob/main/images/framework_logo.jpeg) on the Wikipedia page.

Do you mind that you upload the photo image by yourself there or you declare at least the image with "CC BY-SA 4.0" license? It seems the MIT licence is not allowed to upload it. So, this repository images license might be "MIT or CC BY-SA 4.0".

If you declare the license, I can upload it. However it seems it's less trouble when you, the actual license holder would upload it, seeing other cases.

Here is the [example](https://github.com/FrameworkComputer/Mainboard/blob/main/LICENSE) of "CC BY-SA 4.0" license file on FrameworkComputer/Mainboard repository.

How to upload the image to the Wikipedia: Create your account on Wikipedia, and upload at [UploadWizard](https://commons.wikimedia.org/wiki/Special:UploadWizard). The [document](https://en.wikipedia.org/wiki/Wikipedia:Uploading_images).

Note when you upload a photo file, the file name is directly used to manage the file on Wikipedia, and you cannot change the file name except deleting it. So I would recommend the file name could be identified unique name such as `framedeck_framework_logo.jpeg`.

Thank you!

**Comment by junaruga** [comment]
Here is an example of "MIT or CC BY-SA 4.0". https://github.com/penk/MainboardTerminal/commit/ec24c0ecd101385beadf120c304ea125c5675419

**Comment by brickbots** [comment]
Hello @junaruga !  Thanks for working to maintain the Wikipedia page 👍   I don't have an account on Wikipedia, so I've adjusted the license here to make it more Wikimedia friendly.  Please let me know if you need anything else, I'm happy to help!

**Comment by junaruga** [comment]
All right! Thank you for updating the license. Let me try to upload the photo to Wikipeida, and will let you know.

**Comment by junaruga** [comment]
Your photo was uploaded to the [Framework's Wikipeida page](https://en.wikipedia.org/wiki/Framework_Computer) now! Thank you.
