### ISSUE TITLE
ĄĆŹŻŚĘŁŃÓ 

### ISSUE THREAD

**Issue by xor256** [brickbots/framedeck#3]
how typing polish chars on this keyboard ?
How changing terminal shitf+ctrl+PgUp ?
how closing windows Alt+F4 ?

**Comment by junaruga** [comment]
@xor256 if you use Linux, you can set and switch to your language's keyboard layout by your customized keys on a software level. And there is also a kind of global keyboard layout for extra characters that you shared, called "[compose key](https://rbutterworth.nfshost.com/Tables/compose/)". You can also see `man xkeyboard-config`.
