### ISSUE TITLE
how long this device work?

### ISSUE THREAD

**Issue by xor256** [brickbots/framedeck#4]
A week or month?
I need device with working time twice or more than normal laptop

**Comment by brickbots** [comment]
I've not run the battery out fully yet, but I'd expect it to last a bit less time than the actual framework laptop.  I suspect the HDMI panel I'm using + keyboard MCU + trackball are probably less power efficient than the specific panel, keyboard and trackpad used in the framework laptop.  

It's hard to get that sort of runtime out of any computing device that runs quickly, but you could get there with some low-power ARM systems perhaps if you didn't need a quite as much performance.
