### ISSUE TITLE
How do you access missing keys such as RETURN or SPACE?

### ISSUE THREAD

**Issue by larsblumberg** [brickbots/framedeck#6]
This looks awesome! How do you press ENTER or SPACE though? Does the keyboard use virtual layers that you switch between?

**Comment by brickbots** [comment]
Hi @larsblumberg!  Thanks for checking out my repo and for the great question.  It inspired me to add some information about the keyboard here:

https://github.com/brickbots/framedeck/blob/main/docs/keyboard.md

Hopefully this helps answer some of your questions, but the short of it is that the 6 keys along the bottom have legends which don't match their function.  Enter is the left hand inner thumb button and space is the right hand middle.   

With smaller layouts like this one, it can be tricky to find keycaps that have the right word or symbol on them, so I often just pick ones that look good.
